
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
// Created via this command line: "C:\Users\LeandroGarciaMoreira\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://cashme-dev.api.crm2.dynamics.com" /namespace:"CrmEarlyBound" /SuppressGeneratedCodeAttribute /out:"C:\Users\LeandroGarciaMoreira\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_AccountCategoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente Preferencial", 0)]
		ClientePreferencial = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Padrão", 1)]
		Padrao = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_AccountClassificationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_AccountRatingCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fatura", 0)]
		Fatura = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outro", 3)]
		Outro = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Primário", 2)]
		Primario = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Remessa", 1)]
		Remessa = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FOB", 0)]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Frete Gratuito", 1)]
		FreteGratuito = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente Retira no Local", 4)]
		ClienteRetiranoLocal = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correio Comum", 3)]
		CorreioComum = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DHL", 0)]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FedEx", 1)]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SEDEX", 6)]
		SEDEX = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportadora", 5)]
		Transportadora = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UPS", 2)]
		UPS = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address2_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_BusinessTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Micro Empresa", 3, "#0000ff")]
		MicroEmpresa = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pessoas jurídicas de direito público interno", 1, "#0000ff")]
		Pessoasjuridicasdedireitopublicointerno = 990000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sociedade Civil", 5, "#0000ff")]
		SociedadeCivil = 990000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sociedade Empresária Anônima", 4, "#0000ff")]
		SociedadeEmpresariaAnonima = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sociedade Empresária Limitada", 2, "#0000ff")]
		SociedadeEmpresariaLimitada = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sociedade Individual", 0, "#0000ff")]
		SociedadeIndividual = 990000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_canalencontrouparceiro
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Facebook", 3, "#0000ff")]
		Facebook = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Instagram", 1, "#0000ff")]
		Instagram = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Linkedin", 2, "#0000ff")]
		Linkedin = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portal - Site CashMe", 0, "#0000ff")]
		PortalSiteCashMe = 990000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_destinooperacao
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BNDES", 0, "#0000ff")]
		BNDES = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Planner", 1, "#0000ff")]
		Planner = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_segmentacaoparceiro
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Estruturado", 2, "#0000ff")]
		Estruturado = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Exclusivo", 1, "#0000ff")]
		Exclusivo = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tradicional", 0, "#0000ff")]
		Tradicional = 990000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_situacaocadastral
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ativa", 0, "#0000ff")]
		Ativa = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Baixada", 1, "#0000ff")]
		Baixada = 990000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inapta", 2, "#0000ff")]
		Inapta = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inativa", 3, "#0000ff")]
		Inativa = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nula", 4, "#0000ff")]
		Nula = 990000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Suspensa", 5, "#0000ff")]
		Suspensa = 990000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_status_engajamento
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indicando", 1, "#0000ff")]
		Indicando = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Não indicando", 0, "#0000ff")]
		Naoindicando = 990000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_statuscadastroparceria
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aprovação jurídica confirmada aguardando Treinamento Portal", 2, "#0000ff")]
		AprovacaojuridicaconfirmadaaguardandoTreinamentoPortal = 990000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aprovação jurídica confirmada aguardando Treinamento Produto", 1, "#0000ff")]
		AprovacaojuridicaconfirmadaaguardandoTreinamentoProduto = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aprovação jurídica confirmada aguardando Treinamento Produto e Portal", 3, "#0000ff")]
		AprovacaojuridicaconfirmadaaguardandoTreinamentoProdutoePortal = 990000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cadastrado", 0, "#0000ff")]
		Cadastrado = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Formalizado", 6, "#0000ff")]
		Formalizado = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Treinamentos Portal realizado aguardando aprovação jurídica e Treinamento Produto" +
			"", 5, "#0000ff")]
		TreinamentosPortalrealizadoaguardandoaprovacaojuridicaeTreinamentoProduto = 990000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Treinamentos Produto realizado aguardando aprovação jurídica e Treinamento Portal" +
			"", 4, "#0000ff")]
		TreinamentosProdutorealizadoaguardandoaprovacaojuridicaeTreinamentoPortal = 990000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_csh_temperaturadaparceria
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("🔴 Não tem contrato efetivado nos últimos 90 dias", 3, "#0000ff")]
		Naotemcontratoefetivadonosultimos90dias = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("⚪ Parceiro novo sem contrato efetivado", 0, "#0000ff")]
		Parceironovosemcontratoefetivado = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("🟡 Tem contrato efetivado a + de 30 e - de 90 dias", 2, "#0000ff")]
		Temcontratoefetivadoade30ede90dias = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("🟢 Tem contrato efetivado dentro de 30 dias", 1, "#0000ff")]
		Temcontratoefetivadodentrode30dias = 990000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_CustomerSizeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_CustomerTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Avaliação Cliente", 5)]
		AvaliacaoCliente = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Avaliação de Imóvel", 4)]
		AvaliacaodeImovel = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cartório de imóveis", 7)]
		Cartoriodeimoveis = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cartório de Notas", 8, "#0000ff")]
		CartoriodeNotas = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cessionário", 3)]
		Cessionario = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente", 0)]
		Cliente = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente Potencial", 9)]
		ClientePotencial = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Companhia Hipotecária", 2)]
		CompanhiaHipotecaria = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Instituição Custodiante", 6, "#0000ff")]
		InstituicaoCustodiante = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outro", 10)]
		Outro = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Parceiro - Corretor", 1)]
		ParceiroCorretor = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_IndustryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agricultura", 3)]
		Agricultura = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Água e Saneamento", 17)]
		AguaeSaneamento = 110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alimentos", 9)]
		Alimentos = 79,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bancos", 10)]
		Bancos = 81,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bebidas e Fumo", 18)]
		BebidaseFumo = 111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comércio Atacadista", 1)]
		ComercioAtacadista = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comércio Exterior", 19)]
		ComercioExterior = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comércio Varejista", 6)]
		ComercioVarejista = 72,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Construção Civil", 20)]
		ConstrucaoCivil = 113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Educação", 5)]
		Educacao = 67,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Eletroeletrônico", 2)]
		Eletroeletronico = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Energia Elétrica", 16)]
		EnergiaEletrica = 102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Farmacêutica", 21)]
		Farmaceutica = 114,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Holdings", 22)]
		Holdings = 115,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indústria Automobilística", 12)]
		IndustriaAutomobilistica = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Material de Construção e Decoração", 23)]
		MaterialdeConstrucaoeDecoracao = 116,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mecânica", 24)]
		Mecanica = 117,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Metalurgia", 11)]
		Metalurgia = 89,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mineração", 4)]
		Mineracao = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Papel e Celulose", 25)]
		PapeleCelulose = 118,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Plásticos e Borracha", 26)]
		PlasticoseBorracha = 119,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Química e Petroquímica", 27)]
		QuimicaePetroquimica = 120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Seguros", 0)]
		Seguros = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serviços Especializados", 28)]
		ServicosEspecializados = 121,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serviços Médicos", 8)]
		ServicosMedicos = 78,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Siderurgia", 15)]
		Siderurgia = 94,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tecnologia da Informação", 7)]
		TecnologiadaInformacao = 74,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telecomunicações", 30)]
		Telecomunicacoes = 135,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Têxtil, Couro e Vestuário", 14)]
		TextilCouroeVestuario = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportes e Logística", 13)]
		TransporteseLogistica = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Veículos e Peças", 29)]
		VeiculosePecas = 122,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_OwnershipCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Capital Misto", 2)]
		CapitalMisto = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Particular", 1)]
		Particular = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pública", 0)]
		Publica = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PaymentTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("À Vista", 3)]
		AVista = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vencimento em 30 dias", 0)]
		Vencimentoem30dias = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vencimento em 45 dias", 1)]
		Vencimentoem45dias = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vencimento em 60 dias", 2)]
		Vencimentoem60dias = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PreferredAppointmentDayCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Domingo", 0)]
		Domingo = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quarta-feira", 3)]
		Quartafeira = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quinta-feira", 4)]
		Quintafeira = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sábado", 6)]
		Sabado = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Segunda-feira", 1)]
		Segundafeira = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sexta-feira", 5)]
		Sextafeira = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Terça-feira", 2)]
		Tercafeira = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PreferredAppointmentTimeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Manhã", 0)]
		Manha = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Noite", 2)]
		Noite = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tarde", 1)]
		Tarde = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correio", 4)]
		Correio = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 1)]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fax", 3)]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualquer uma", 0)]
		Qualqueruma = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telefone", 2)]
		Telefone = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ativa", 0)]
		Ativa = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inativa", 1)]
		Inativa = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_TerritoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BudgetStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comprará", 3)]
		Comprara = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nenhum Orçamento Comprometido", 0)]
		NenhumOrcamentoComprometido = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pode Comprar", 2)]
		PodeComprar = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Possível Comprar", 1)]
		PossivelComprar = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bzp_tipoespecificoimovel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Apartamento Padrão", 0)]
		ApartamentoPadrao = 329300000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Casa em Condomínio", 10)]
		CasaemCondominio = 329300010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Casa Geminada", 9)]
		CasaGeminada = 329300009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Casa Padrão", 8)]
		CasaPadrao = 329300008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cobertura", 7)]
		Cobertura = 329300007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comercial", 15)]
		Comercial = 329300015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Duplex", 5)]
		Duplex = 329300005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Flat", 2)]
		Flat = 329300002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Galpão", 18)]
		Galpao = 329300018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Loft", 3)]
		Loft = 329300003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outros", 16)]
		Outros = 329300016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quitinete", 1)]
		Quitinete = 329300001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sobrado em Condomínio", 13)]
		SobradoemCondominio = 329300013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sobrado Geminado", 12)]
		SobradoGeminado = 329300012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sobrado Padrão", 11)]
		SobradoPadrao = 329300011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Studio", 4)]
		Studio = 329300004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Terreno", 14)]
		Terreno = 329300014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Triplex", 6)]
		Triplex = 329300006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vaga", 17)]
		Vaga = 329300017,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bzp_tipogenericoimovel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Apartamento", 0)]
		Apartamento = 329300000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Casa", 1)]
		Casa = 329300001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outros", 2)]
		Outros = 329300002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_AccountRoleCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Funcionário", 1)]
		Funcionario = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Influenciador", 2)]
		Influenciador = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tomador de Decisão", 0)]
		TomadordeDecisao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fatura", 0)]
		Fatura = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outro", 3)]
		Outro = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Primário", 2)]
		Primario = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Remessa", 1)]
		Remessa = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FOB", 0)]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Frete Gratuito", 1)]
		FreteGratuito = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente Retira no Local", 4)]
		ClienteRetiranoLocal = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correio Comum", 3)]
		CorreioComum = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DHL", 0)]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FedEx", 1)]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SEDEX", 6)]
		SEDEX = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportadora", 5)]
		Transportadora = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UPS", 2)]
		UPS = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_CustomerSizeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_CustomerTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente", 1)]
		Cliente = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Colaborador", 0, "#0000ff")]
		Colaborador = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_EducationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FamilyStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Casado(a)", 1)]
		Casadoa = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Divorciado(a)", 2)]
		Divorciadoa = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separado", 4, "#0000ff")]
		Separado = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Solteiro", 0)]
		Solteiro = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("União Estável", 5, "#0000ff")]
		UniaoEstavel = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Viúvo(a)", 3)]
		Viuvoa = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_GenderCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Feminino", 1)]
		Feminino = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Masculino", 0)]
		Masculino = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_HasChildrenCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_LeadSourceCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_msdyn_orgchangestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fora da Empresa", 1, "#0000ff")]
		ForadaEmpresa = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ignorar", 2, "#0000ff")]
		Ignorar = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sem Comentários", 0, "#0000ff")]
		SemComentarios = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PaymentTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("À Vista", 3)]
		AVista = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vencimento em 30 dias", 0)]
		Vencimentoem30dias = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vencimento em 45 dias", 1)]
		Vencimentoem45dias = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vencimento em 60 dias", 2)]
		Vencimentoem60dias = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredAppointmentDayCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Domingo", 0)]
		Domingo = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quarta-feira", 3)]
		Quartafeira = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quinta-feira", 4)]
		Quintafeira = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sábado", 6)]
		Sabado = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Segunda-feira", 1)]
		Segundafeira = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sexta-feira", 5)]
		Sextafeira = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Terça-feira", 2)]
		Tercafeira = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredAppointmentTimeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Manhã", 0)]
		Manha = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Noite", 2)]
		Noite = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tarde", 1)]
		Tarde = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correio", 4)]
		Correio = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 1)]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fax", 3)]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualquer uma", 0)]
		Qualqueruma = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telefone", 2)]
		Telefone = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ativa", 0)]
		Ativa = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inativa", 1)]
		Inativa = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_TerritoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_naturezaocupacao
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aposentado ou Pensionista", 3, "#0000ff")]
		AposentadoouPensionista = 990000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Assalariado (CLT)", 0, "#0000ff")]
		AssalariadoCLT = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Autônomo", 2, "#0000ff")]
		Autonomo = 990000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Do Lar", 8, "#0000ff")]
		DoLar = 990000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Empresário", 1, "#0000ff")]
		Empresario = 990000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Funcionário Público", 4, "#0000ff")]
		FuncionarioPublico = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prestador de Serviços", 5, "#0000ff")]
		PrestadordeServicos = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Profissional Liberal", 6, "#0000ff")]
		ProfissionalLiberal = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Renda de Aluguéis", 7, "#0000ff")]
		RendadeAlugueis = 990000005,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_RegimeMatrimonial
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão de bens", 0, "#0000ff", "validar??", "1")]
		Comunhaodebens = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão parcial de bens", 1, "#0000ff", "remover??", "3")]
		Comunhaoparcialdebens = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão parcial de bens, antes da vigência da Lei 6.515/77", 2, "#0000ff", "", "6")]
		ComunhaoparcialdebensantesdavigenciadaLei651577 = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão parcial de bens, na vigência da Lei 6.515/77", 3, "#0000ff", "", "7")]
		ComunhaoparcialdebensnavigenciadaLei651577 = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão universal de bens", 4, "#0000ff", "", "8")]
		Comunhaouniversaldebens = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão universal de bens, antes da vigência da Lei 6.515/77", 5, "#0000ff", "", "9")]
		ComunhaouniversaldebensantesdavigenciadaLei651577 = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comunhão universal de bens, na vigência da Lei 6.515/77", 6, "#0000ff", "", "12")]
		ComunhaouniversaldebensnavigenciadaLei651577 = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Participação final nos aqüestos", 7, "#0000ff", "", "47")]
		Participacaofinalnosaquestos = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação de bens", 8, "#0000ff", "", "50")]
		Separacaodebens = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação de bens, antes da vigência da Lei 6.515/77", 10, "#0000ff", "", "52")]
		SeparacaodebensantesdavigenciadaLei651577 = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação de bens, na vigência da Lei 6.515/77", 11, "#0000ff", "", "53")]
		SeparacaodebensnavigenciadaLei651577 = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação obrigatória de bens", 9, "#0000ff", "", "54")]
		Separacaoobrigatoriadebens = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação parcial, antes da vigência da Lei 6.515/77", 12, "#0000ff", "", "55")]
		SeparacaoparcialantesdavigenciadaLei651577 = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação parcial, na vigência da Lei 6.515/77", 13, "#0000ff", "", "56")]
		SeparacaoparcialnavigenciadaLei651577 = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Separação total de bens, na vigência da Lei 6.515/77", 14, "#0000ff", "", "57")]
		SeparacaototaldebensnavigenciadaLei651577 = 15,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_SetoresEmpresa
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agropecuária", 0, "#0000ff")]
		Agropecuaria = 990000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comercio", 1, "#0000ff")]
		Comercio = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Construção Civil", 2, "#0000ff")]
		ConstrucaoCivil = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Industria", 3, "#0000ff")]
		Industria = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serviços", 4, "#0000ff")]
		Servicos = 990000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_status_permissao_opcao
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opt-In", 0)]
		OptIn = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opt-Out", 1)]
		OptOut = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum InitialCommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contatado", 0)]
		Contatado = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Não Contatado", 1)]
		NaoContatado = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_csh_contatoinicial
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desnecessário", 2, "#0000ff")]
		Desnecessario = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pendente", 1, "#0000ff")]
		Pendente = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Realizado", 0, "#0000ff")]
		Realizado = 990000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_csh_ramoatuacao
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consultoria Empresarial", 1, "#0000ff")]
		ConsultoriaEmpresarial = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consultoria Financeira", 0, "#0000ff")]
		ConsultoriaFinanceira = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correspondência Bancária", 2, "#0000ff")]
		CorrespondenciaBancaria = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Imobiliário", 3, "#0000ff")]
		Imobiliario = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outro", 5, "#0000ff")]
		Outro = 990000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tecnologia", 4, "#0000ff")]
		Tecnologia = 990000004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_csh_tempodeatuacao
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("2 a 5 anos", 1, "#0000ff")]
		_2a5anos = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Até 1 ano", 0, "#0000ff")]
		Ate1ano = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mais de 5 anos", 2, "#0000ff")]
		Maisde5anos = 990000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_csh_tipoclientepotencial
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Parceiro Potencial", 0, "#0000ff")]
		ParceiroPotencial = 990000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_IndustryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agricultura", 3)]
		Agricultura = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Água e Saneamento", 17)]
		AguaeSaneamento = 110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alimentos", 9)]
		Alimentos = 79,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bancos", 10)]
		Bancos = 81,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bebidas e Fumo", 18)]
		BebidaseFumo = 111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comércio Atacadista", 1)]
		ComercioAtacadista = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comércio Exterior", 19)]
		ComercioExterior = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comércio Varejista", 6)]
		ComercioVarejista = 72,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Construção Civil", 20)]
		ConstrucaoCivil = 113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Educação", 5)]
		Educacao = 67,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Eletroeletrônico", 2)]
		Eletroeletronico = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Energia Elétrica", 16)]
		EnergiaEletrica = 102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Farmacêutica", 21)]
		Farmaceutica = 114,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Holdings", 22)]
		Holdings = 115,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indústria Automobilística", 12)]
		IndustriaAutomobilistica = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Material de Construção e Decoração", 23)]
		MaterialdeConstrucaoeDecoracao = 116,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mecânica", 24)]
		Mecanica = 117,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Metalurgia", 11)]
		Metalurgia = 89,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mineração", 4)]
		Mineracao = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Papel e Celulose", 25)]
		PapeleCelulose = 118,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Plásticos e Borracha", 26)]
		PlasticoseBorracha = 119,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Química e Petroquímica", 27)]
		QuimicaePetroquimica = 120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Seguros", 0)]
		Seguros = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serviços Especializados", 28)]
		ServicosEspecializados = 121,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serviços Médicos", 8)]
		ServicosMedicos = 78,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Siderurgia", 15)]
		Siderurgia = 94,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tecnologia da Informação", 7)]
		TecnologiadaInformacao = 74,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telecomunicações", 30)]
		Telecomunicacoes = 135,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Têxtil, Couro e Vestuário", 14)]
		TextilCouroeVestuario = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportes e Logística", 13)]
		TransporteseLogistica = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Veículos e Peças", 29)]
		VeiculosePecas = 122,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_LeadQualityCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Interessado", 1)]
		Interessado = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Muito Interessado", 0)]
		MuitoInteressado = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sem interesse", 2)]
		Seminteresse = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_LeadSourceCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Anúncio", 4)]
		Anuncio = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Boca-a-Boca", 2)]
		BocaaBoca = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Facebook", 11, "#0000ff")]
		Facebook = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Feira de Negócios", 5)]
		FeiradeNegocios = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Formulário Patrocinado do LinkedIn", 15, "#0077B5")]
		FormularioPatrocinadodoLinkedIn = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indicação de Funcionário", 6)]
		IndicacaodeFuncionario = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indicação de outro Parceiro", 8)]
		IndicacaodeoutroParceiro = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indicação Externa", 7)]
		IndicacaoExterna = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Instagram", 12, "#0000ff")]
		Instagram = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Linkedin", 13, "#0000ff")]
		Linkedin = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outro", 3)]
		Outro = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Página de aterrissagem", 14)]
		Paginadeaterrissagem = 192350100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portal - Site", 9, "#0000ff")]
		PortalSite = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Relações Públicas", 0)]
		RelacoesPublicas = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Seminário", 10)]
		Seminario = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web", 1)]
		Web = 8,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_msdyn_salesassignmentresult
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Êxito", 0, "#0000ff")]
		Exito = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falha", 1, "#000fff")]
		Falha = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_msdyncrm_leadsourcetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cliente potencial contatado por telefone", 2, "#0000ff")]
		Clientepotencialcontatadoportelefone = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marketing", 0, "#0000ff")]
		Marketing = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vendas", 1, "#0000ff")]
		Vendas = 192350001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correio", 4)]
		Correio = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 1)]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fax", 3)]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualquer uma", 0)]
		Qualqueruma = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telefone", 2)]
		Telefone = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_PriorityCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_SalesStage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualificar", 0)]
		Qualificar = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_SalesStageCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Valor Padrão", 0)]
		ValorPadrao = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("1. Pré Cadastro", 0, "#0000ff")]
		_1PreCadastro = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("2. Cadastrado", 1, "#0000ff")]
		_2Cadastrado = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("3. Em processo de formalização", 2, "#0000ff")]
		_3Emprocessodeformalizacao = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("4. Formalizado", 3, "#0000ff")]
		_4Formalizado = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cancelado", 8, "#0000ff")]
		Cancelado = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Não É Possível Contatar", 6, "#0000ff")]
		NaoEPossivelContatar = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Não Está Mais Interessado", 7, "#0000ff")]
		NaoEstaMaisInteressado = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Perdido", 5, "#0000ff")]
		Perdido = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualificado", 4, "#0000ff")]
		Qualificado = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_leadgradeoptset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Classificação A", 0, "#0000ff")]
		ClassificacaoA = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Classificação B", 1, "#0000ff")]
		ClassificacaoB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Classificação C", 2, "#0000ff")]
		ClassificacaoC = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Classificação D", 3, "#0000ff")]
		ClassificacaoD = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_leadscoretrendoptset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Em Declínio", 2, "#0000ff")]
		EmDeclinio = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Estável", 1, "#0000ff")]
		Estavel = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Informações insuficientes", 3, "#0000ff")]
		Informacoesinsuficientes = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Melhorando", 0, "#0000ff")]
		Melhorando = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msevtmgt_nooryes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Não", 0, "#0000ff")]
		Nao = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sim", 1, "#0000ff")]
		Sim = 100000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msgdpr_gdpr_consent_option_set
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(1) Consentimento", 0, "#0000ff")]
		_1Consentimento = 587030001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(2) Transacional", 1, "#0000ff")]
		_2Transacional = 587030002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(3) Assinaturas", 2, "#0000ff")]
		_3Assinaturas = 587030003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(4) Marketing", 3, "#0000ff")]
		_4Marketing = 587030004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("(5) Criação de perfil", 4, "#0000ff")]
		_5Criacaodeperfil = 587030005,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Need
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Deve ter", 1)]
		Deveter = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("É bom ter", 2)]
		Ebomter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("É obrigatório ter", 0)]
		Eobrigatorioter = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sem necessidades", 3)]
		Semnecessidades = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PurchaseProcess
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comissão", 1)]
		Comissao = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desconhecido", 2)]
		Desconhecido = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Individual", 0)]
		Individual = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PurchaseTimeFrame
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desconhecido", 4)]
		Desconhecido = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Este Ano", 3)]
		EsteAno = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Este Trimestre", 1)]
		EsteTrimestre = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Imediato", 0)]
		Imediato = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Próximo Trimestre", 2)]
		ProximoTrimestre = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appaction_clienttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Navegador", 0, "#0000ff")]
		Navegador = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dispositivo móvel", 1, "#0000ff")]
		Dispositivomovel = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aplicativo de email", 2, "#0000ff")]
		Aplicativodeemail = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_servico_csh_OpcoesQuodRelatorio
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dados Cadastrais", 0, "#0000ff", "IncludeBestInfo")]
		DadosCadastrais = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indicador Consulta e Negativação", 1, "#0000ff", "IncludeCreditRiskIndicators")]
		IndicadorConsultaeNegativacao = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Detalhes de Consultas e Negativações", 2, "#0000ff", "IncludeCreditRiskData")]
		DetalhesdeConsultaseNegativacoes = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Score", 3, "#0000ff", "IncludeQuodScore")]
		Score = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dados Positivos", 4, "#0000ff", "IncludeCreditLinesData")]
		DadosPositivos = 5,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_servico_csh_IndicadoresQuod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_PRD01", 0, "#0000ff")]
		PF_PC_PRD01 = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_PRD02", 1, "#0000ff")]
		PF_PC_PRD02 = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_VLR01", 2, "#0000ff")]
		PF_PC_VLR01 = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_TPR01", 3, "#0000ff")]
		PF_PC_TPR01 = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_TPR02", 4, "#0000ff")]
		PF_PC_TPR02 = 990000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_CPR01", 5, "#0000ff")]
		PF_PC_CPR01 = 990000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_PC_CPR02", 6, "#0000ff")]
		PF_PC_CPR02 = 990000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_EM_ITS01", 7, "#0000ff")]
		PF_EM_ITS01 = 990000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_EM_ITS02", 8, "#0000ff")]
		PF_EM_ITS02 = 990000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_EM_HBT01", 9, "#0000ff")]
		PF_EM_HBT01 = 990000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_EM_HBT02", 10, "#0000ff")]
		PF_EM_HBT02 = 990000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_CP_CNT01", 11, "#0000ff")]
		PF_CP_CNT01 = 990000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_CP_VOL01", 12, "#0000ff")]
		PF_CP_VOL01 = 990000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_CP_VOL02", 13, "#0000ff")]
		PF_CP_VOL02 = 990000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_CP_VOL03", 14, "#0000ff")]
		PF_CP_VOL03 = 990000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PF_CP_VOL04", 15, "#0000ff")]
		PF_CP_VOL04 = 990000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_AMP01", 16, "#0000ff")]
		PP_AV_AMP01 = 990000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_AMP02", 17, "#0000ff")]
		PP_AV_AMP02 = 990000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_GRV01", 18, "#0000ff")]
		PP_AV_GRV01 = 990000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_GRV02", 19, "#0000ff")]
		PP_AV_GRV02 = 990000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_GRV03", 20, "#0000ff")]
		PP_AV_GRV03 = 990000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_GRV04", 21, "#0000ff")]
		PP_AV_GRV04 = 990000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_MRC01", 22, "#0000ff")]
		PP_AV_MRC01 = 990000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_MRC02", 23, "#0000ff")]
		PP_AV_MRC02 = 990000023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_TDC01", 24, "#0000ff")]
		PP_AV_TDC01 = 990000024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_AV_TDC02", 25, "#0000ff")]
		PP_AV_TDC02 = 990000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_HA_AMP01", 26, "#0000ff")]
		PP_HA_AMP01 = 990000026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_HA_AMP02", 27, "#0000ff")]
		PP_HA_AMP02 = 990000027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_HA_REC01", 28, "#0000ff")]
		PP_HA_REC01 = 990000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_HA_FRQ_01", 29, "#0000ff")]
		PP_HA_FRQ_01 = 990000029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_HA_VLR01", 30, "#0000ff")]
		PP_HA_VLR01 = 990000030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_HA_VLR02", 31, "#0000ff")]
		PP_HA_VLR02 = 990000031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_PD_CPG01", 32, "#0000ff")]
		PP_PD_CPG01 = 990000032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_PD_CPG02", 33, "#0000ff")]
		PP_PD_CPG02 = 990000033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PP_PD_PPG01", 34, "#0000ff")]
		PP_PD_PPG01 = 990000034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_BC_REC01", 35, "#0000ff")]
		RM_BC_REC01 = 990000035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_BC_REC02", 36, "#0000ff")]
		RM_BC_REC02 = 990000036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_BC_FRQ01", 37, "#0000ff")]
		RM_BC_FRQ01 = 990000037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_AMP01", 38, "#0000ff")]
		RM_PR_AMP01 = 990000038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_ETB01", 39, "#0000ff")]
		RM_PR_ETB01 = 990000039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_ETB02", 40, "#0000ff")]
		RM_PR_ETB02 = 990000040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_MOD01", 41, "#0000ff")]
		RM_PR_MOD01 = 990000041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_MOD02", 42, "#0000ff")]
		RM_PR_MOD02 = 990000042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_MOD03", 43, "#0000ff")]
		RM_PR_MOD03 = 990000043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RM_PR_MOD04", 44, "#0000ff")]
		RM_PR_MOD04 = 990000044,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_forecastsettingsandsummary_msdyn_forecastjobstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sucesso", 0, "#0000ff")]
		Sucesso = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falha de Dados", 1, "#0000ff")]
		FalhadeDados = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falha no Pipeline", 2, "#0000ff")]
		FalhanoPipeline = 192350002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_knowledgemanagementsetting_msdyn_actionlist
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vincular/desvincular artigo", 0, "#0000ff")]
		Vinculardesvincularartigo = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copiar URL", 1, "#0000ff")]
		CopiarURL = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vincular artigo e URL do email", 2, "#0000ff")]
		VincularartigoeURLdoemail = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vincular artigo e enviar conteúdo do artigo", 3, "#0000ff")]
		Vincularartigoeenviarconteudodoartigo = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocapplepay_msdyn_merchantcapabilities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Débito", 0, "#0000ff")]
		Debito = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Crédito", 1, "#0000ff")]
		Credito = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("3D Seguro", 2, "#0000ff")]
		_3DSeguro = 192350002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_ocapplepay_msdyn_supportednetworks
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("American Express", 0, "#0000ff")]
		AmericanExpress = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Visa", 1, "#0000ff")]
		Visa = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Discover", 2, "#0000ff")]
		Discover = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MasterCard", 3, "#0000ff")]
		MasterCard = 192350003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_oc_daysofweek
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dom", 0, "#0000ff")]
		Dom = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Seg", 1, "#0000ff")]
		Seg = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ter", 2, "#0000ff")]
		Ter = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qua", 3, "#0000ff")]
		Qua = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qui", 4, "#0000ff")]
		Qui = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sex", 5, "#0000ff")]
		Sex = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sáb", 6, "#0000ff")]
		Sab = 192350006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum csh_systemuser_csh_area_atuacao
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comercial", 0, "#0000ff")]
		Comercial = 990000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Crédito", 1, "#0000ff")]
		Credito = 990000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gestão de Ativos", 2, "#0000ff")]
		GestaodeAtivos = 990000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Jurídico", 3, "#0000ff")]
		Juridico = 990000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pré-Comite", 4, "#0000ff")]
		PreComite = 990000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comitê", 5, "#0000ff")]
		Comite = 990000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Formalização", 6, "#0000ff")]
		Formalizacao = 990000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Registro", 7, "#0000ff")]
		Registro = 990000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Financeiro", 8, "#0000ff")]
		Financeiro = 990000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marketing", 9, "#0000ff")]
		Marketing = 990000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Relacionamento", 10, "#0000ff")]
		Relacionamento = 990000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cobrança", 11, "#0000ff")]
		Cobranca = 990000011,
	}
}
